<?php

namespace DoctrineORMModule\Proxy\__CG__\ORM\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Usuario extends \ORM\Entity\Usuario implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'ORM\\Entity\\Usuario' . "\0" . 'usuarioNickname', '' . "\0" . 'ORM\\Entity\\Usuario' . "\0" . 'usuarioNombres', '' . "\0" . 'ORM\\Entity\\Usuario' . "\0" . 'usuarioApellidos', '' . "\0" . 'ORM\\Entity\\Usuario' . "\0" . 'usuarioTipoDoc', '' . "\0" . 'ORM\\Entity\\Usuario' . "\0" . 'usuarioNumDoc', '' . "\0" . 'ORM\\Entity\\Usuario' . "\0" . 'usuarioTelefono', '' . "\0" . 'ORM\\Entity\\Usuario' . "\0" . 'usuarioEmail', '' . "\0" . 'ORM\\Entity\\Usuario' . "\0" . 'usuarioFechaRegistro', '' . "\0" . 'ORM\\Entity\\Usuario' . "\0" . 'meGustaCompartirCompartir', '' . "\0" . 'ORM\\Entity\\Usuario' . "\0" . 'usuariocatCatalogo', '' . "\0" . 'ORM\\Entity\\Usuario' . "\0" . 'usuarioCompraCompra');
        }

        return array('__isInitialized__', '' . "\0" . 'ORM\\Entity\\Usuario' . "\0" . 'usuarioNickname', '' . "\0" . 'ORM\\Entity\\Usuario' . "\0" . 'usuarioNombres', '' . "\0" . 'ORM\\Entity\\Usuario' . "\0" . 'usuarioApellidos', '' . "\0" . 'ORM\\Entity\\Usuario' . "\0" . 'usuarioTipoDoc', '' . "\0" . 'ORM\\Entity\\Usuario' . "\0" . 'usuarioNumDoc', '' . "\0" . 'ORM\\Entity\\Usuario' . "\0" . 'usuarioTelefono', '' . "\0" . 'ORM\\Entity\\Usuario' . "\0" . 'usuarioEmail', '' . "\0" . 'ORM\\Entity\\Usuario' . "\0" . 'usuarioFechaRegistro', '' . "\0" . 'ORM\\Entity\\Usuario' . "\0" . 'meGustaCompartirCompartir', '' . "\0" . 'ORM\\Entity\\Usuario' . "\0" . 'usuariocatCatalogo', '' . "\0" . 'ORM\\Entity\\Usuario' . "\0" . 'usuarioCompraCompra');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Usuario $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getUsuarioNickname()
    {
        if ($this->__isInitialized__ === false) {
            return  parent::getUsuarioNickname();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsuarioNickname', array());

        return parent::getUsuarioNickname();
    }

    /**
     * {@inheritDoc}
     */
    public function setUsuarioNombres($usuarioNombres)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUsuarioNombres', array($usuarioNombres));

        return parent::setUsuarioNombres($usuarioNombres);
    }

    /**
     * {@inheritDoc}
     */
    public function getUsuarioNombres()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsuarioNombres', array());

        return parent::getUsuarioNombres();
    }

    /**
     * {@inheritDoc}
     */
    public function setUsuarioApellidos($usuarioApellidos)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUsuarioApellidos', array($usuarioApellidos));

        return parent::setUsuarioApellidos($usuarioApellidos);
    }

    /**
     * {@inheritDoc}
     */
    public function getUsuarioApellidos()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsuarioApellidos', array());

        return parent::getUsuarioApellidos();
    }

    /**
     * {@inheritDoc}
     */
    public function setUsuarioTipoDoc($usuarioTipoDoc)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUsuarioTipoDoc', array($usuarioTipoDoc));

        return parent::setUsuarioTipoDoc($usuarioTipoDoc);
    }

    /**
     * {@inheritDoc}
     */
    public function getUsuarioTipoDoc()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsuarioTipoDoc', array());

        return parent::getUsuarioTipoDoc();
    }

    /**
     * {@inheritDoc}
     */
    public function setUsuarioNumDoc($usuarioNumDoc)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUsuarioNumDoc', array($usuarioNumDoc));

        return parent::setUsuarioNumDoc($usuarioNumDoc);
    }

    /**
     * {@inheritDoc}
     */
    public function getUsuarioNumDoc()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsuarioNumDoc', array());

        return parent::getUsuarioNumDoc();
    }

    /**
     * {@inheritDoc}
     */
    public function setUsuarioTelefono($usuarioTelefono)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUsuarioTelefono', array($usuarioTelefono));

        return parent::setUsuarioTelefono($usuarioTelefono);
    }

    /**
     * {@inheritDoc}
     */
    public function getUsuarioTelefono()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsuarioTelefono', array());

        return parent::getUsuarioTelefono();
    }

    /**
     * {@inheritDoc}
     */
    public function setUsuarioEmail($usuarioEmail)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUsuarioEmail', array($usuarioEmail));

        return parent::setUsuarioEmail($usuarioEmail);
    }

    /**
     * {@inheritDoc}
     */
    public function getUsuarioEmail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsuarioEmail', array());

        return parent::getUsuarioEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function setUsuarioFechaRegistro($usuarioFechaRegistro)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUsuarioFechaRegistro', array($usuarioFechaRegistro));

        return parent::setUsuarioFechaRegistro($usuarioFechaRegistro);
    }

    /**
     * {@inheritDoc}
     */
    public function getUsuarioFechaRegistro()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsuarioFechaRegistro', array());

        return parent::getUsuarioFechaRegistro();
    }

    /**
     * {@inheritDoc}
     */
    public function getMeGustaCompartirCompartir()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMeGustaCompartirCompartir', array());

        return parent::getMeGustaCompartirCompartir();
    }

    /**
     * {@inheritDoc}
     */
    public function getUsuariocatCatalogo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsuariocatCatalogo', array());

        return parent::getUsuariocatCatalogo();
    }

    /**
     * {@inheritDoc}
     */
    public function getUsuarioCompraCompra()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsuarioCompraCompra', array());

        return parent::getUsuarioCompraCompra();
    }

}
