<?php

namespace DoctrineORMModule\Proxy\__CG__\ORM\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Rol extends \ORM\Entity\Rol implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'ORM\\Entity\\Rol' . "\0" . 'rolIdRol', '' . "\0" . 'ORM\\Entity\\Rol' . "\0" . 'rolDescripcion', '' . "\0" . 'ORM\\Entity\\Rol' . "\0" . 'rolFecha', '' . "\0" . 'ORM\\Entity\\Rol' . "\0" . 'rolNombre', '' . "\0" . 'ORM\\Entity\\Rol' . "\0" . 'rolmoduModulo');
        }

        return array('__isInitialized__', '' . "\0" . 'ORM\\Entity\\Rol' . "\0" . 'rolIdRol', '' . "\0" . 'ORM\\Entity\\Rol' . "\0" . 'rolDescripcion', '' . "\0" . 'ORM\\Entity\\Rol' . "\0" . 'rolFecha', '' . "\0" . 'ORM\\Entity\\Rol' . "\0" . 'rolNombre', '' . "\0" . 'ORM\\Entity\\Rol' . "\0" . 'rolmoduModulo');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Rol $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getRolIdRol()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getRolIdRol();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRolIdRol', array());

        return parent::getRolIdRol();
    }

    /**
     * {@inheritDoc}
     */
    public function setRolDescripcion($rolDescripcion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRolDescripcion', array($rolDescripcion));

        return parent::setRolDescripcion($rolDescripcion);
    }

    /**
     * {@inheritDoc}
     */
    public function getRolDescripcion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRolDescripcion', array());

        return parent::getRolDescripcion();
    }

    /**
     * {@inheritDoc}
     */
    public function setRolFecha($rolFecha)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRolFecha', array($rolFecha));

        return parent::setRolFecha($rolFecha);
    }

    /**
     * {@inheritDoc}
     */
    public function getRolFecha()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRolFecha', array());

        return parent::getRolFecha();
    }

    /**
     * {@inheritDoc}
     */
    public function setRolNombre($rolNombre)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRolNombre', array($rolNombre));

        return parent::setRolNombre($rolNombre);
    }

    /**
     * {@inheritDoc}
     */
    public function getRolNombre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRolNombre', array());

        return parent::getRolNombre();
    }

    /**
     * {@inheritDoc}
     */
    public function getRolmoduModulo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRolmoduModulo', array());

        return parent::getRolmoduModulo();
    }

}
