<?php

namespace DoctrineORMModule\Proxy\__CG__\ORM\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Producto extends \ORM\Entity\Producto implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'ORM\\Entity\\Producto' . "\0" . 'productoIdProducto', '' . "\0" . 'ORM\\Entity\\Producto' . "\0" . 'productoNombre', '' . "\0" . 'ORM\\Entity\\Producto' . "\0" . 'productoDescripcion', '' . "\0" . 'ORM\\Entity\\Producto' . "\0" . 'productoFoto', '' . "\0" . 'ORM\\Entity\\Producto' . "\0" . 'productoFechaCreacion', '' . "\0" . 'ORM\\Entity\\Producto' . "\0" . 'productoEstado', '' . "\0" . 'ORM\\Entity\\Producto' . "\0" . 'otroTipoOtroTipo');
        }

        return array('__isInitialized__', '' . "\0" . 'ORM\\Entity\\Producto' . "\0" . 'productoIdProducto', '' . "\0" . 'ORM\\Entity\\Producto' . "\0" . 'productoNombre', '' . "\0" . 'ORM\\Entity\\Producto' . "\0" . 'productoDescripcion', '' . "\0" . 'ORM\\Entity\\Producto' . "\0" . 'productoFoto', '' . "\0" . 'ORM\\Entity\\Producto' . "\0" . 'productoFechaCreacion', '' . "\0" . 'ORM\\Entity\\Producto' . "\0" . 'productoEstado', '' . "\0" . 'ORM\\Entity\\Producto' . "\0" . 'otroTipoOtroTipo');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Producto $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getProductoIdProducto()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getProductoIdProducto();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProductoIdProducto', array());

        return parent::getProductoIdProducto();
    }

    /**
     * {@inheritDoc}
     */
    public function setProductoNombre($productoNombre)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProductoNombre', array($productoNombre));

        return parent::setProductoNombre($productoNombre);
    }

    /**
     * {@inheritDoc}
     */
    public function getProductoNombre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProductoNombre', array());

        return parent::getProductoNombre();
    }

    /**
     * {@inheritDoc}
     */
    public function setProductoDescripcion($productoDescripcion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProductoDescripcion', array($productoDescripcion));

        return parent::setProductoDescripcion($productoDescripcion);
    }

    /**
     * {@inheritDoc}
     */
    public function getProductoDescripcion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProductoDescripcion', array());

        return parent::getProductoDescripcion();
    }

    /**
     * {@inheritDoc}
     */
    public function setProductoFoto($productoFoto)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProductoFoto', array($productoFoto));

        return parent::setProductoFoto($productoFoto);
    }

    /**
     * {@inheritDoc}
     */
    public function getProductoFoto()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProductoFoto', array());

        return parent::getProductoFoto();
    }

    /**
     * {@inheritDoc}
     */
    public function setProductoFechaCreacion($productoFechaCreacion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProductoFechaCreacion', array($productoFechaCreacion));

        return parent::setProductoFechaCreacion($productoFechaCreacion);
    }

    /**
     * {@inheritDoc}
     */
    public function getProductoFechaCreacion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProductoFechaCreacion', array());

        return parent::getProductoFechaCreacion();
    }

    /**
     * {@inheritDoc}
     */
    public function setProductoEstado($productoEstado)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProductoEstado', array($productoEstado));

        return parent::setProductoEstado($productoEstado);
    }

    /**
     * {@inheritDoc}
     */
    public function getProductoEstado()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProductoEstado', array());

        return parent::getProductoEstado();
    }

    /**
     * {@inheritDoc}
     */
    public function addOtroTipoOtroTipo(\ORM\Entity\OtroTipoProducto $otroTipoOtroTipo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addOtroTipoOtroTipo', array($otroTipoOtroTipo));

        return parent::addOtroTipoOtroTipo($otroTipoOtroTipo);
    }

    /**
     * {@inheritDoc}
     */
    public function removeOtroTipoOtroTipo(\ORM\Entity\OtroTipoProducto $otroTipoOtroTipo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeOtroTipoOtroTipo', array($otroTipoOtroTipo));

        return parent::removeOtroTipoOtroTipo($otroTipoOtroTipo);
    }

    /**
     * {@inheritDoc}
     */
    public function getOtroTipoOtroTipo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOtroTipoOtroTipo', array());

        return parent::getOtroTipoOtroTipo();
    }

}
