               <!-- Header -->
              <header>
                  <div class="container">
                      <div class="row">
                          <div class="col-lg-12">
                              <img src="<?= $this->basePath('landing_page/img/profile.png') ?>" alt=""/>
                              <div class="intro-text">
                                  <span class="name">Coffee Market House</span>
                                  <hr class="star-light">
                                  <span class="skills">EL MEJOR CAFÉ DE FINCA A UN CLICK DE DISTANCIA</span>
                              </div>
                          </div>
                      </div>
                  </div>
              </header>

              <!-- Portfolio Grid Section -->
              <section id="portfolio">
                  <div class="container">
                      <div class="row">
                          <div class="col-lg-12 text-center">
                              <h2>NUESTROS PRODUCTOS</h2>
                              <hr class="star-primary">
                          </div>
                      </div>
                      <div class="row">
                          <div class="col-sm-4 portfolio-item">
                              <a href="#portfolioModal1" class="portfolio-link" data-toggle="modal">
                                  <div class="caption">
                                      <div class="caption-content">
                                          <i class="fa fa-search-plus fa-3x"></i>
                                      </div>
                                  </div>
                                  <img src="<?= $this->basePath('landing_page/img/portfolio/cabin.png') ?>" class="img-responsive" alt="">
                              </a>
                          </div>
                          <div class="col-sm-4 portfolio-item">
                              <a href="#portfolioModal2" class="portfolio-link" data-toggle="modal">
                                  <div class="caption">
                                      <div class="caption-content">
                                          <i class="fa fa-search-plus fa-3x"></i>
                                      </div>
                                  </div>
                                  <img src="<?= $this->basePath('landing_page/img/portfolio/cake.png') ?>" class="img-responsive" alt="">
                              </a>
                          </div>
                          <div class="col-sm-4 portfolio-item">
                              <a href="#portfolioModal3" class="portfolio-link" data-toggle="modal">
                                  <div class="caption">
                                      <div class="caption-content">
                                          <i class="fa fa-search-plus fa-3x"></i>
                                      </div>
                                  </div>
                                  <img src="<?= $this->basePath('landing_page/img/portfolio/circus.png') ?>" class="img-responsive" alt="">
                              </a>
                          </div>
                        </div>
                  </div>
              </section>

              <!-- Suscripciones -->
              <section id="suscrip">
                  <div class="container">
                      <div class="row">
                          <div class="col-lg-12 text-center">
                              <h2>SUSCRIPCIONES</h2>
                              <hr class="star-primary">
                          </div>
                      </div>
                      <div class="row">
                          <div class="col-sm-3 portfolio-item">
                              <a href="#suscripModal1" class="portfolio-link" data-toggle="modal">
                                  <div class="caption">
                                      <div class="caption-content">
                                          <i class="fa fa-search-plus fa-3x"></i>
                                      </div>
                                  </div>
                                  <img src="<?= $this->basePath('landing_page/img/portfolio/game.png') ?>" class="img-responsive" alt="">
                              </a>
                          </div>
                          <div class="col-sm-3 portfolio-item">
                              <a href="#suscripModal2" class="portfolio-link" data-toggle="modal">
                                  <div class="caption">
                                      <div class="caption-content">
                                          <i class="fa fa-search-plus fa-3x"></i>
                                      </div>
                                  </div>
                                  <img src="<?= $this->basePath('landing_page/img/portfolio/safe.png') ?>" class="img-responsive" alt="">
                              </a>
                          </div>
                          <div class="col-sm-3 portfolio-item">
                              <a href="#suscripModal3" class="portfolio-link" data-toggle="modal">
                                  <div class="caption">
                                      <div class="caption-content">
                                          <i class="fa fa-search-plus fa-3x"></i>
                                      </div>
                                  </div>
                                  <img src="<?= $this->basePath('landing_page/img/portfolio/submarine.png') ?>" class="img-responsive" alt="">
                              </a>
                          </div>
                          <div class="col-sm-3 portfolio-item">
                              <a href="#suscripModal4" class="portfolio-link" data-toggle="modal">
                                  <div class="caption">
                                      <div class="caption-content">
                                          <i class="fa fa-search-plus fa-3x"></i>
                                      </div>
                                  </div>
                                  <img src="<?= $this->basePath('landing_page/img/portfolio/submarine.png') ?>" class="img-responsive" alt="">
                              </a>
                          </div>
                      </div>
                  </div>
              </section>


              <!-- About Suscripciones -->
              <section class="success" id="about_suscrip">
                  <div class="container">
                      <div class="row">
                          <div class="col-lg-12 text-center">
                              <h2>QUIENES SOMOS</h2>
                              <hr class="star-light">
                          </div>
                      </div>
                      <div class="row">
                          <div class="col-lg-4 col-lg-offset-2">
                              <p>Coffee Market House&reg; es la primera tienda virtual de café del mejor café de finca, con una comunidad de amantes del café en constante crecimiento que giran entorno a nuestro producto y servicio. En Coffee Market House&reg; contamos con diferentes servicios, entre ellos la compra del exquisito café de finca por medio 3 formas de suscripción. </p>
                          </div>
                          <div class="col-lg-4">
                              <p>También contamos con nuestra comunidad de proveedores, cuyo objetivo es comercializar su inigualable producto traido directamente del arból para que usted lo prepare. Coffee Market House&reg; el mejor café de finca a un click de distancia</p>
                          </div>
                          <div class="col-lg-8 col-lg-offset-2 text-center">
                              <a href="#" class="btn btn-lg btn-outline" style="background-color:#ff5733">
                                  <i class="fa fa-download"></i> Sí, quiero unirme
                              </a>
                          </div>
                      </div>
                  </div>
              </section>


              <!-- Contact Section -->
              <section id="contact">
                  <div class="container">
                      <div class="row">
                          <div class="col-lg-12 text-center">
                              <h2>Contacta con nosotros</h2>
                              <hr class="star-primary">
                          </div>
                      </div>
                      <div class="row">
                          <div class="col-lg-8 col-lg-offset-2">
                              <!-- To configure the contact form email address, go to mail/contact_me.php and update the email address in the PHP file on line 19. -->
                              <!-- The form should work on most web servers, but if the form is not working you may need to configure your web server differently. -->
                              <form name="sentMessage" id="contactForm" novalidate>
                                  <div class="row control-group">
                                      <div class="form-group col-xs-12 floating-label-form-group controls">
                                          <label>Nombre</label>
                                          <input type="text" class="form-control" placeholder="Nombre" id="name" required data-validation-required-message="Ingresa tu mejor nombre.">
                                          <p class="help-block text-danger"></p>
                                      </div>
                                  </div>
                                  <div class="row control-group">
                                      <div class="form-group col-xs-12 floating-label-form-group controls">
                                          <label>Email</label>
                                          <input type="email" class="form-control" placeholder="Email" id="email" required data-validation-required-message="Ingresa tu mejor e-mail.">
                                          <p class="help-block text-danger"></p>
                                      </div>
                                  </div>
                                  <div class="row control-group">
                                      <div class="form-group col-xs-12 floating-label-form-group controls">
                                          <label>Teléfono</label>
                                          <input type="tel" class="form-control" placeholder="Teléfono" id="phone" required data-validation-required-message="Por favor ingresa tu teléfono.">
                                          <p class="help-block text-danger"></p>
                                      </div>
                                  </div>
                                  <div class="row control-group">
                                      <div class="form-group col-xs-12 floating-label-form-group controls">
                                          <label>Mensaje</label>
                                          <textarea rows="5" class="form-control" placeholder="Mensaje" id="message" required data-validation-required-message="Por favor ingresa tu mensaje."></textarea>
                                          <p class="help-block text-danger"></p>
                                      </div>
                                  </div>
                                  <br>
                                  <div id="success"></div>
                                  <div class="row">
                                      <div class="form-group col-xs-12">
                                          <button type="submit" class="btn btn-success btn-lg">Enviar</button>
                                      </div>
                                  </div>
                              </form>
                          </div>
                      </div>
                  </div>
              </section>

              <!-- Scroll to Top Button (Only visible on small and extra-small screen sizes) -->
              <div class="scroll-top page-scroll hidden-sm hidden-xs hidden-lg hidden-md">
                  <a class="btn btn-primary" href="#page-top">
                      <i class="fa fa-chevron-up"></i>
                  </a>
              </div>

              <!-- Portfolio Modals -->
              <div class="portfolio-modal modal fade" id="portfolioModal1" tabindex="-1" role="dialog" aria-hidden="true">
                  <div class="modal-content">
                      <div class="close-modal" data-dismiss="modal">
                          <div class="lr">
                              <div class="rl">
                              </div>
                          </div>
                      </div>
                      <div class="container">
                          <div class="row">
                              <div class="col-lg-8 col-lg-offset-2">
                                  <div class="modal-body">
                                      <h2>Project Title</h2>
                                      <hr class="star-primary">
                                      <img src="<?= $this->basePath('landing_page/img/portfolio/cabin.png') ?>" class="img-responsive img-centered" alt="">
                                      <p>Use this area of the page to describe your project. The icon above is part of a free icon set by <a href="https://sellfy.com/p/8Q9P/jV3VZ/">Flat Icons</a>. On their website, you can download their free set with 16 icons, or you can purchase the entire set with 146 icons for only $12!</p>
                                      <ul class="list-inline item-details">
                                          <li>Client:
                                              <strong><a href="http://startbootstrap.com">Start Bootstrap</a>
                                              </strong>
                                          </li>
                                          <li>Date:
                                              <strong><a href="http://startbootstrap.com">April 2014</a>
                                              </strong>
                                          </li>
                                          <li>Service:
                                              <strong><a href="http://startbootstrap.com">Web Development</a>
                                              </strong>
                                          </li>
                                      </ul>
                                      <button type="button" class="btn btn-default" data-dismiss="modal"><i class="fa fa-times"></i> Close</button>
                                  </div>
                              </div>
                          </div>
                      </div>
                  </div>
              </div>
              <div class="portfolio-modal modal fade" id="portfolioModal2" tabindex="-1" role="dialog" aria-hidden="true">
                  <div class="modal-content">
                      <div class="close-modal" data-dismiss="modal">
                          <div class="lr">
                              <div class="rl">
                              </div>
                          </div>
                      </div>
                      <div class="container">
                          <div class="row">
                              <div class="col-lg-8 col-lg-offset-2">
                                  <div class="modal-body">
                                      <h2>Project Title</h2>
                                      <hr class="star-primary">
                                      <img src="<?= $this->basePath('landing_page/img/portfolio/cake.png') ?>" class="img-responsive img-centered" alt="">
                                      <p>Use this area of the page to describe your project. The icon above is part of a free icon set by <a href="https://sellfy.com/p/8Q9P/jV3VZ/">Flat Icons</a>. On their website, you can download their free set with 16 icons, or you can purchase the entire set with 146 icons for only $12!</p>
                                      <ul class="list-inline item-details">
                                          <li>Client:
                                              <strong><a href="http://startbootstrap.com">Start Bootstrap</a>
                                              </strong>
                                          </li>
                                          <li>Date:
                                              <strong><a href="http://startbootstrap.com">April 2014</a>
                                              </strong>
                                          </li>
                                          <li>Service:
                                              <strong><a href="http://startbootstrap.com">Web Development</a>
                                              </strong>
                                          </li>
                                      </ul>
                                      <button type="button" class="btn btn-default" data-dismiss="modal"><i class="fa fa-times"></i> Close</button>
                                  </div>
                              </div>
                          </div>
                      </div>
                  </div>
              </div>
              <div class="portfolio-modal modal fade" id="portfolioModal3" tabindex="-1" role="dialog" aria-hidden="true">
                  <div class="modal-content">
                      <div class="close-modal" data-dismiss="modal">
                          <div class="lr">
                              <div class="rl">
                              </div>
                          </div>
                      </div>
                      <div class="container">
                          <div class="row">
                              <div class="col-lg-8 col-lg-offset-2">
                                  <div class="modal-body">
                                      <h2>Project Title</h2>
                                      <hr class="star-primary">
                                      <img src="<?= $this->basePath('landing_page/img/portfolio/circus.png') ?>" class="img-responsive img-centered" alt="">
                                      <p>Use this area of the page to describe your project. The icon above is part of a free icon set by <a href="https://sellfy.com/p/8Q9P/jV3VZ/">Flat Icons</a>. On their website, you can download their free set with 16 icons, or you can purchase the entire set with 146 icons for only $12!</p>
                                      <ul class="list-inline item-details">
                                          <li>Client:
                                              <strong><a href="http://startbootstrap.com">Start Bootstrap</a>
                                              </strong>
                                          </li>
                                          <li>Date:
                                              <strong><a href="http://startbootstrap.com">April 2014</a>
                                              </strong>
                                          </li>
                                          <li>Service:
                                              <strong><a href="http://startbootstrap.com">Web Development</a>
                                              </strong>
                                          </li>
                                      </ul>
                                      <button type="button" class="btn btn-default" data-dismiss="modal"><i class="fa fa-times"></i> Close</button>
                                  </div>
                              </div>
                          </div>
                      </div>
                  </div>
              </div>
              <div class="portfolio-modal modal fade" id="suscripModal1" tabindex="-1" role="dialog" aria-hidden="true">
                  <div class="modal-content">
                      <div class="close-modal" data-dismiss="modal">
                          <div class="lr">
                              <div class="rl">
                              </div>
                          </div>
                      </div>
                      <div class="container">
                          <div class="row">
                              <div class="col-lg-8 col-lg-offset-2">
                                  <div class="modal-body">
                                      <h2>Project Title</h2>
                                      <hr class="star-primary">
                                      <img src="<?= $this->basePath('landing_page/img/portfolio/game.png') ?>" class="img-responsive img-centered" alt="">
                                      <p>Use this area of the page to describe your project. The icon above is part of a free icon set by <a href="https://sellfy.com/p/8Q9P/jV3VZ/">Flat Icons</a>. On their website, you can download their free set with 16 icons, or you can purchase the entire set with 146 icons for only $12!</p>
                                      <ul class="list-inline item-details">
                                          <li>Client:
                                              <strong><a href="http://startbootstrap.com">Start Bootstrap</a>
                                              </strong>
                                          </li>
                                          <li>Date:
                                              <strong><a href="http://startbootstrap.com">April 2014</a>
                                              </strong>
                                          </li>
                                          <li>Service:
                                              <strong><a href="http://startbootstrap.com">Web Development</a>
                                              </strong>
                                          </li>
                                      </ul>
                                      <button type="button" class="btn btn-default" data-dismiss="modal"><i class="fa fa-times"></i> Close</button>
                                  </div>
                              </div>
                          </div>
                      </div>
                  </div>
              </div>
              <div class="portfolio-modal modal fade" id="suscripModal2" tabindex="-1" role="dialog" aria-hidden="true">
                  <div class="modal-content">
                      <div class="close-modal" data-dismiss="modal">
                          <div class="lr">
                              <div class="rl">
                              </div>
                          </div>
                      </div>
                      <div class="container">
                          <div class="row">
                              <div class="col-lg-8 col-lg-offset-2">
                                  <div class="modal-body">
                                      <h2>Project Title</h2>
                                      <hr class="star-primary">
                                      <img src="<?= $this->basePath('landing_page/img/portfolio/safe.png') ?>" class="img-responsive img-centered" alt="">
                                      <p>Use this area of the page to describe your project. The icon above is part of a free icon set by <a href="https://sellfy.com/p/8Q9P/jV3VZ/">Flat Icons</a>. On their website, you can download their free set with 16 icons, or you can purchase the entire set with 146 icons for only $12!</p>
                                      <ul class="list-inline item-details">
                                          <li>Client:
                                              <strong><a href="http://startbootstrap.com">Start Bootstrap</a>
                                              </strong>
                                          </li>
                                          <li>Date:
                                              <strong><a href="http://startbootstrap.com">April 2014</a>
                                              </strong>
                                          </li>
                                          <li>Service:
                                              <strong><a href="http://startbootstrap.com">Web Development</a>
                                              </strong>
                                          </li>
                                      </ul>
                                      <button type="button" class="btn btn-default" data-dismiss="modal"><i class="fa fa-times"></i> Close</button>
                                  </div>
                              </div>
                          </div>
                      </div>
                  </div>
              </div>
              <div class="portfolio-modal modal fade" id="suscripModal3" tabindex="-1" role="dialog" aria-hidden="true">
                  <div class="modal-content">
                      <div class="close-modal" data-dismiss="modal">
                          <div class="lr">
                              <div class="rl">
                              </div>
                          </div>
                      </div>
                      <div class="container">
                          <div class="row">
                              <div class="col-lg-8 col-lg-offset-2">
                                  <div class="modal-body">
                                      <h2>Project Title</h2>
                                      <hr class="star-primary">
                                      <img src="<?= $this->basePath('landing_page/img/portfolio/submarine.png') ?>" class="img-responsive img-centered" alt="">
                                      <p>Use this area of the page to describe your project. The icon above is part of a free icon set by <a href="https://sellfy.com/p/8Q9P/jV3VZ/">Flat Icons</a>. On their website, you can download their free set with 16 icons, or you can purchase the entire set with 146 icons for only $12!</p>
                                      <ul class="list-inline item-details">
                                          <li>Client:
                                              <strong><a href="http://startbootstrap.com">Start Bootstrap</a>
                                              </strong>
                                          </li>
                                          <li>Date:
                                              <strong><a href="http://startbootstrap.com">April 2014</a>
                                              </strong>
                                          </li>
                                          <li>Service:
                                              <strong><a href="http://startbootstrap.com">Web Development</a>
                                              </strong>
                                          </li>
                                      </ul>
                                      <button type="button" class="btn btn-default" data-dismiss="modal"><i class="fa fa-times"></i> Close</button>
                                  </div>
                              </div>
                          </div>
                      </div>
                  </div>
              </div>
              <div class="portfolio-modal modal fade" id="suscripModal4" tabindex="-1" role="dialog" aria-hidden="true">
                  <div class="modal-content">
                      <div class="close-modal" data-dismiss="modal">
                          <div class="lr">
                              <div class="rl">
                              </div>
                          </div>
                      </div>
                      <div class="container">
                          <div class="row">
                              <div class="col-lg-8 col-lg-offset-2">
                                  <div class="modal-body">
                                      <h2>Project Title</h2>
                                      <hr class="star-primary">
                                      <img src="<?= $this->basePath('landing_page/img/portfolio/submarine.png') ?>" class="img-responsive img-centered" alt="">
                                      <p>Use this area of the page to describe your project. The icon above is part of a free icon set by <a href="https://sellfy.com/p/8Q9P/jV3VZ/">Flat Icons</a>. On their website, you can download their free set with 16 icons, or you can purchase the entire set with 146 icons for only $12!</p>
                                      <ul class="list-inline item-details">
                                          <li>Client:
                                              <strong><a href="http://startbootstrap.com">Start Bootstrap</a>
                                              </strong>
                                          </li>
                                          <li>Date:
                                              <strong><a href="http://startbootstrap.com">April 2014</a>
                                              </strong>
                                          </li>
                                          <li>Service:
                                              <strong><a href="http://startbootstrap.com">Web Development</a>
                                              </strong>
                                          </li>
                                      </ul>
                                      <button type="button" class="btn btn-default" data-dismiss="modal"><i class="fa fa-times"></i> Close</button>
                                  </div>
                              </div>
                          </div>
                      </div>
                  </div>
              </div>