<div class="col-sm-6 register-box">
          <div class="register-logo">
            <a href="../../index2.html"><b>Coffee</b> Market</a>
          </div>

          <div class="register-box-body">
            <p class="login-box-msg">Registrar un nuevo amante del café</p>

            <form action="../../index.html" method="post">

              <div class="row">
                <div class="col-lg-6 form-group has-feedback">
                  <span class="glyphicon glyphicon-user form-control-feedback"></span>
                  <input type="text" class="form-control" placeholder="Nombres">
                </div>
                <div class="col-lg-6 form-group has-feedback">
                  <input type="email" class="form-control" placeholder="Apellidos">
                  <span class="glyphicon glyphicon-envelope form-control-feedback"></span>
                </div>
              </div>
              <div class="row">
                <div class="col-lg-4 form-group has-feedback">
                  <input type="password" class="form-control" placeholder="Teléfono">
                  <span class="glyphicon glyphicon-lock form-control-feedback"></span>
                </div>
                <div class="col-lg-4 form-group has-feedback">
                  <input type="password" class="form-control" placeholder="Celular">
                  <span class="glyphicon glyphicon-log-in form-control-feedback"></span>
                </div>
                <div class="col-lg-4 form-group has-feedback">
                  <input type="password" class="form-control" placeholder="Email">
                  <span class="glyphicon glyphicon-log-in form-control-feedback"></span>
                </div>
              </div>
              <div class="row">
                <div class="col-lg-4 form-group has-feedback">
                  <input type="password" class="form-control" placeholder="Número de Documento">
                  <span class="glyphicon glyphicon-lock form-control-feedback"></span>
                </div>
                <div class="col-lg-4 form-group has-feedback">
                  <input type="password" class="form-control" placeholder="Dirección 1">
                  <span class="glyphicon glyphicon-log-in form-control-feedback"></span>
                </div>
                <div class="col-lg-4 form-group has-feedback">
                  <input type="password" class="form-control" placeholder="Dirección 2">
                  <span class="glyphicon glyphicon-log-in form-control-feedback"></span>
                </div>
              </div>
              <div class="row">
                <div class="col-lg-4 form-group has-feedback">
                  <label for="sel1">Tipo de Documento:</label>
                    <select class="form-control" id="sel1">
                      <option>1</option>
                      <option>2</option>
                      <option>3</option>
                      <option>4</option>
                    </select>
                  
                </div>
              </div>
             <div class="row">
                <div class="col-lg-4 form-group has-feedback">
                  <input type="password" class="form-control" placeholder="Usuario">
                  <span class="glyphicon glyphicon-lock form-control-feedback"></span>
                </div>
                <div class="col-lg-4 form-group has-feedback">
                  <input type="password" class="form-control" placeholder="Contraseña">
                  <span class="glyphicon glyphicon-log-in form-control-feedback"></span>
                </div>
                <div class="col-lg-4 form-group has-feedback">
                  <input type="password" class="form-control" placeholder="Confirme su Contraseña">
                  <span class="glyphicon glyphicon-log-in form-control-feedback"></span>
                </div>
              </div>
              <div class="row">
                <div class="col-lg-12">
                  &sbn;
                </div>
              </div>
              <div class="row">
                <div class="col-lg-4">
                  <div class="checkbox icheck">
                    <label>
                      <input type="checkbox"> I agree to the <a href="#">terms</a>
                    </label>
                  </div>
                </div>
                <!-- /.col -->
                <div class="col-lg-4">
                  <button type="submit" class="btn btn-primary btn-block btn-flat">Register</button>
                </div>
                <!-- /.col -->
              </div>
            </form>

            <div class="social-auth-links text-center">
              <p>- OR -</p>
              <a href="#" class="btn btn-block btn-social btn-facebook btn-flat"><i class="fa fa-facebook"></i> Sign up using
                Facebook</a>
              <a href="#" class="btn btn-block btn-social btn-google btn-flat"><i class="fa fa-google-plus"></i> Sign up using
                Google+</a>
            </div>

            <a href="<?= $this->basePath('cuenta/login') ?>" class="text-center">I already have a membership</a>
          </div>
          <!-- /.form-box -->
        </div>
        <!-- /.register-box -->

        <div class="row">
          <div class="col-sm-9">
            Level 1: .col-sm-9
            
          </div>
        </div>