<!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <h1>
        ERROR DE ACCESO
      </h1>
      <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> Dedes estar logeado para acceder a este recurso</a></li>
      </ol>
    </section>

    <!-- Main content -->
    <section class="content">

      <div class="error-page">
        <h2 class="headline text-red">ERROR</h2>

        <div class="error-content">
          <h3><i class="fa fa-warning text-red"></i> Oops! Al parecer no puedes ingresar al sistema. Por favor da click al siguiente enlace para acceder al login de la aplicacion <a href="<?= $this->basePath('cuenta/login') ?>">AQUI</a></h3>

        </div>
      </div>
      <!-- /.error-page -->

    </section>
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->