<?= $this->doctype() ?>

<html lang="en">
    <head>

        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="description" content="">
        <meta name="author" content="">

        <title>Coofee Market House</title>


        <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
            <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
            <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
        <![endif]-->


        <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
            ->prependStylesheet($this->basePath('landing_page/css/freelancer.min.css'))
            ->prependStylesheet($this->basePath('landing_page/vendor/bootstrap/css/bootstrap.min.css'))
            ->prependStylesheet($this->basePath('landing_page/vendor/font-awesome/css/font-awesome.min.css'))
            ?>
            <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">
            <link href="https://fonts.googleapis.com/css?family=Lato:400,700,400italic,700italic" rel="stylesheet" type="text/css" rel="stylesheet" type="text/css">
        <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
            
            ->prependStylesheet($this->basePath('landing_page/css/pace-theme-flash.css'))
        ?>

        <!-- Scripts -->
        <?= $this->headScript()

            /*<!-- Bootstrap Core JavaScript -->*/
            ->prependFile($this->basePath('landing_page/vendor/bootstrap/js/bootstrap.min.js'))

            /*<!-- Plugin JavaScript -->*/
            ->appendFile('https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.3/jquery.easing.min.js','text/javascript')

            /*<!-- Contact Form JavaScript -->*/
            ->prependFile($this->basePath('landing_page/js/jqBootstrapValidation.js'))
            ->prependFile($this->basePath('landing_page/js/contact_me.js'))


            /*<!-- jQuery -->*/
            ->prependFile($this->basePath('landing_page/vendor/jquery/jquery.min.js'))

            /*<!-- Theme JavaScript -->*/
            ->prependFile($this->basePath('landing_page/js/freelancer.js'))

            /*pace.min*/
            ->prependFile($this->basePath('landing_page/js/pace.min.js'))

        ?>



    </head>

    <body body id="page-top" class="index">



        <!-- Se despliega el contenido-->
        <?= $this->content ?>

        <!-- Scripts -->
        <?= $this->headScript() ?>

    </body>

</html>