<?php echo $this->doctype(); ?>

<html lang="es">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('Coffee Market House' . $this->translate('Admin'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php
        echo $this->headMeta()
                ->appendName('viewport', 'width=device-width, initial-scale=1.0')
                ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

          <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
            ->prependStylesheet($this->basePath('social/bootstrap/css/bootstrap.min.css'))
            ->prependStylesheet($this->basePath('social/dist/css/AdminLTE.min.css'))
            ->prependStylesheet($this->basePath('social/plugins/iCheck/square/blue.css'))
            ->prependStylesheet($this->basePath('landing_page/css/pace-theme-flash.css'))
          ?>

          <!-- Font Awesome -->
          <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.5.0/css/font-awesome.min.css">
          <!-- Ionicons -->
          <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css">


          <?= $this->headScript()

              /*pace.min*/
              ->prependFile($this->basePath('landing_page/js/pace.min.js'))

          ?>

          <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
          <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
          <!--[if lt IE 9]>
          <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
          <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
          <![endif]-->
        </head>
        <body class="hold-transition register-page">
        
          
          <!-- Se despliega el contenido-->
          <?= $this->content ?>

          <!-- Scripts -->
          <?= $this->headScript() ?>

        <script src="<?= $this->basePath('social/plugins/jQuery/jquery-2.2.3.min.js') ?>"></script>
        <script src="<?= $this->basePath('social/bootstrap/js/bootstrap.min.js') ?>"></script>
        <script src="<?= $this->basePath('social/plugins/iCheck/icheck.min.js') ?>"></script>

        <script>
          $(function () {
            $('input').iCheck({
              checkboxClass: 'icheckbox_square-blue',
              radioClass: 'iradio_square-blue',
              increaseArea: '20%' // optional
            });
          });
        </script>
        </body>
        </html>
