<?= $this->doctype() ?>

<html lang="en">
    <head>

        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="description" content="">
        <meta name="author" content="">

        <title>Coofee Market House</title>


        <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
            <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
            <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
        <![endif]-->


        <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])

            ->prependStylesheet($this->basePath('landing_page/css/freelancer.min.css'))
            ->prependStylesheet($this->basePath('social/plugins/iCheck/square/blue.css'))
            ->prependStylesheet($this->basePath('css/toastr/toastr.css'))

            ->prependStylesheet($this->basePath('landing_page/vendor/bootstrap/css/bootstrap.min.css'))
            ->prependStylesheet($this->basePath('landing_page/vendor/font-awesome/css/font-awesome.min.css'))
            ->prependStylesheet($this->basePath('social/plugins/fileinput/fileinput.css'))
            ->prependStylesheet($this->basePath('social/plugins/select2/select2.css'))

            ?>
            <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">
            <link href="https://fonts.googleapis.com/css?family=Lato:400,700,400italic,700italic" rel="stylesheet" type="text/css" rel="stylesheet" type="text/css">
        <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
            
            ->prependStylesheet($this->basePath('landing_page/css/pace-theme-flash.css'))
        ?>

        <!-- Scripts -->
        <?= $this->headScript()

            /*<!-- Bootstrap Core JavaScript -->*/
            ->prependFile($this->basePath('landing_page/vendor/bootstrap/js/bootstrap.min.js'))

            ->prependFile($this->basePath('social/plugins/iCheck/icheck.min.js'))
            ->prependFile($this->basePath('js/controllers/httpPetition.js'))
            ->prependFile($this->basePath('js/controllers/toast.js'))
            ->prependFile($this->basePath('js/toastr/toastr.js'))


            /*<!-- Plugin JavaScript -->*/
            ->appendFile('https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.3/jquery.easing.min.js','text/javascript')

            /*<!-- Contact Form JavaScript -->*/

            /*
            ->prependFile($this->basePath('landing_page/js/jqBootstrapValidation.js'))
            ->prependFile($this->basePath('landing_page/js/contact_me.js'))
            */


            /*<!-- jQuery -->*/
            ->prependFile($this->basePath('landing_page/vendor/jquery/jquery.min.js'))

            /*<!-- Theme JavaScript -->*/
            ->prependFile($this->basePath('landing_page/js/freelancer.js'))

            /*pace.min*/
            ->prependFile($this->basePath('landing_page/js/pace.min.js'))

        ?>



    </head>

    <body body id="page-top" class="index">

        <!-- Navigation -->
        <nav id="mainNav" class="navbar navbar-default navbar-fixed-top navbar-custom">
             <div class="container">
                 <!-- Brand and toggle get grouped for better mobile display -->
                 <div class="navbar-header page-scroll">
                     <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                         <span class="sr-only">Toggle navigation</span> Menu <i class="fa fa-bars"></i>
                     </button>
                     <a class="navbar-brand" href="<?= $this->basePath('/') ?>" style="background-color:#ff5733">Coffee Market</a>
                 </div>

                 <!-- Collect the nav links, forms, and other content for toggling -->
                 <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                     <ul class="nav navbar-nav navbar-right">
                         <li class="hidden">
                             <a href="#page-top"></a>
                         </li>
                         <li class="page-scroll">
                             <a href="<?= $this->basePath('cuenta/register') ?>">Registro</a>
                         </li>
                         <li class="page-scroll">
                             <a href="<?= $this->basePath('cuenta/login') ?>">Login</a>
                         </li>
                     </ul>
                 </div>
                 <!-- /.navbar-collapse -->
             </div>
         <!-- /.container-fluid -->
        </nav>

        <div class="container" style="margin:150px auto;">
            <!-- Se despliega el contenido-->
            <?= $this->content ?>
        </div>  


        <!-- Footer -->
        <footer class="text-center">
            <div class="footer-above">
                <div class="container">
                    <div class="row">
                        <div class="footer-col col-md-4">
                            <h3>Ubicación</h3>
                            <p>Cali, Colombia
                                <br>Universidad del Valle</p>
                        </div>
                        <div class="footer-col col-md-4">
                            <h3>Acerca de Nuestra Web</h3>
                            <ul class="list-inline">
                                <li>
                                    <a href="#" class="btn-social btn-outline"><i class="fa fa-fw fa-facebook"></i></a>
                                </li>
                                <li>
                                    <a href="#" class="btn-social btn-outline"><i class="fa fa-fw fa-google-plus"></i></a>
                                </li>
                                <li>
                                    <a href="#" class="btn-social btn-outline"><i class="fa fa-fw fa-twitter"></i></a>
                                </li>
                                <li>
                                    <a href="#" class="btn-social btn-outline"><i class="fa fa-fw fa-linkedin"></i></a>
                                </li>
                                <li>
                                    <a href="#" class="btn-social btn-outline"><i class="fa fa-fw fa-dribbble"></i></a>
                                </li>
                            </ul>
                        </div>
                        <div class="footer-col col-md-4">
                            <h3>ACERCA DE AMXSOFT</h3>
                            <p>AMXSOFT es una empresa diseñadora de sofware y aplicaciones web</a>.</p>
                        </div>
                    </div>
                </div>
            </div>
            <div class="footer-below">
                <div class="container">
                    <div class="row">
                        <div class="col-lg-12">
                            Copyright &copy; Coffe Market House 2016
                        </div>
                    </div>
                </div>
            </div>
        </footer>

        <script>
          $(function () {
            $('input').iCheck({
              checkboxClass: 'icheckbox_square-blue',
              radioClass: 'iradio_square-blue',
              increaseArea: '50%' // optional
            });
          });
        </script>

        <!-- Scripts -->
        <?= $this->headScript() ?>
        <script src="<?= $this->basePath('js/controllers/Define.js') ?>" ></script>
        <script src="<?= $this->basePath('js/controllers/cuenta.js') ?>" ></script>
        <script src="<?= $this->basePath('social/plugins/select2/select2.js') ?>"></script>

    </body>

</html>